const recyclingFacts = [
  "Recycling one aluminum can saves enough energy to run a TV for 3 hours.",
  "Glass can be recycled endlessly without losing quality or purity.",
  "Recycling one ton of paper saves 17 trees and over 7,000 gallons of water.",
  "Plastic bottles can take up to 450 years to decompose in landfills.",
  "Recycling one ton of aluminum saves 14,000 kWh of energy.",
  "Recycling helps reduce greenhouse gas emissions by lowering demand for raw materials.",
  "The energy saved from recycling one glass bottle can power a light bulb for 4 hours.",
  "About 75% of aluminum ever produced is still in use today.",
  "Every ton of recycled plastic saves nearly 2,000 gallons of gasoline.",
  "Producing recycled paper uses 60% less energy than making paper from new materials.",
  "One recycled tin can saves enough energy to run a computer for 25 minutes.",
  "Every plastic bag you recycle saves valuable landfill space and reduces pollution.",
  "Americans throw away enough office paper each year to build a 12-foot-high wall from New York to California.",
  "The average person generates over 4 pounds of trash every single day.",
  "Recycling one glass bottle saves enough energy to charge a smartphone for an entire week.",
  "Recycling reduces the need for mining, logging, and drilling — preserving natural habitats.",
  "Composting food waste can reduce landfill methane emissions by up to 50%.",
  "Steel is the most recycled material in the world, with a recycling rate of over 85%.",
  "Recycling just one plastic bottle saves enough energy to power a 60-watt light bulb for 6 hours.",
  "E-waste recycling helps recover valuable metals like gold, silver, and copper.",
  "Paper can be recycled up to 7 times before the fibers become too weak.",
  "Recycling one ton of steel saves 2,500 pounds of iron ore and 1,400 pounds of coal.",
  "Organic waste makes up about 30% of what we throw away and could be composted instead.",
  "Recycling reduces ocean pollution by keeping plastics out of waterways.",
  "Every ton of recycled cardboard saves 46 gallons of oil.",
  "If every American recycled just one-tenth of their newspapers, 25 million trees could be saved each year.",
  "Recycling saves money, creates jobs, and conserves natural resources.",
];

export default recyclingFacts;
